module.exports = `
type AspectoComportamentalBS{
  aspecto_comportamenta_bs_id:ID!
  estudiante_id:Int
  expresivo:String!
  amistoso:String!
  entusiasta:String!
  inconstante:String!
  independiente:String!
  trabajador:String!
  irascible:String!
  tomadecisiones:String!
  autodiciplinado:String!
  ansioso:String!
  calmadotranquilo:String!
  buenhumor:String!
  lentotrabajar:String!
  organizado:String!
  autocritico:String!
  iinquieto:String!
  distraido:String!
  dependiente:String!
  motivacion:String!
  convivencia:String!
  insegurointrovertido:String!
  trabajarequipo:String!
  cuestaemociones:String!
  organizadoactividades:String!
  otropsicologico:String!
  otropsiquiatrico:String!
  otroterapiaocupacional:String!
  otroterapialenguaje:String!
  fonoaudilogia:String!
  fisioterapia:String!
  otro:String!
  cual:String
  observaciones:String
}

`